-- Створення таблиці речей
create table public.items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  name text not null,
  category text not null,
  season text not null,
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Створення таблиці образів (луків)
create table public.looks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  title text default 'Мій образ',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Створення таблиці зв'язку речей з образами (з координатами для конструктора)
create table public.look_items (
  id bigint generated by default as identity primary key,
  look_id bigint references public.looks on delete cascade not null,
  item_id bigint references public.items on delete cascade not null,
  x real not null default 50,
  y real not null default 50,
  z_index integer not null default 1,
  scale real not null default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Налаштування безпеки (Row Level Security)
alter table public.items enable row level security;
alter table public.looks enable row level security;
alter table public.look_items enable row level security;

-- Політики для таблиці items (кожен бачить і змінює тільки своє)
create policy "Users can view own items" on public.items for select using (auth.uid() = user_id);
create policy "Users can insert own items" on public.items for insert with check (auth.uid() = user_id);
create policy "Users can update own items" on public.items for update using (auth.uid() = user_id);
create policy "Users can delete own items" on public.items for delete using (auth.uid() = user_id);

-- Політики для таблиці looks
create policy "Users can view own looks" on public.looks for select using (auth.uid() = user_id);
create policy "Users can insert own looks" on public.looks for insert with check (auth.uid() = user_id);
create policy "Users can update own looks" on public.looks for update using (auth.uid() = user_id);
create policy "Users can delete own looks" on public.looks for delete using (auth.uid() = user_id);

-- Політики для таблиці look_items
create policy "Users can view own look_items" on public.look_items for select using (
  exists (select 1 from public.looks where id = look_items.look_id and user_id = auth.uid())
);
create policy "Users can insert own look_items" on public.look_items for insert with check (
  exists (select 1 from public.looks where id = look_items.look_id and user_id = auth.uid())
);
create policy "Users can update own look_items" on public.look_items for update using (
  exists (select 1 from public.looks where id = look_items.look_id and user_id = auth.uid())
);
create policy "Users can delete own look_items" on public.look_items for delete using (
  exists (select 1 from public.looks where id = look_items.look_id and user_id = auth.uid())
);

-- Створення сховища для фотографій (Storage)
insert into storage.buckets (id, name, public) values ('wardrobe_images', 'wardrobe_images', true);

-- Безпека сховища
create policy "Public Access" on storage.objects for select using (bucket_id = 'wardrobe_images');
create policy "Auth Insert" on storage.objects for insert with check (bucket_id = 'wardrobe_images' and auth.role() = 'authenticated');
create policy "Auth Delete" on storage.objects for delete using (bucket_id = 'wardrobe_images' and auth.uid() = owner);
